export default[
    {   air:"AIRINDIA",
        img:"airIndia.svg",
        price:"3000",
        fromCity:"AMD",
        fromTime:"08:10",
        toCity:"BOM",
        toTime:"09:40",
        duration:"1h 30m",
        service:"Free Wifi, In Flight Entertainment",
    },
    {
        air:"AIRINDIA",
        img:"airIndia.svg",
        price:"3000",
        fromCity:"AMD",
        fromTime:"16:30",
        toCity:"BOM",
        toTime:"18:00",
        duration:"1h 30m",
        service:"Free Wifi",
    },
    {
        air:"INDIGO",
        img:"airIndia.svg",
        price:"3000",
        fromCity:"AMD",
        fromTime:"11:10",
        toCity:"BOM",
        toTime:"13:40",
        duration:"1h 30m",
        service:"In Flight Entertainment",
    },
]